phases:
  install:
    runtime-versions:
      nodejs: 14  # Especifico la versi贸n de Node.js
    commands:
      - echo "Instalando dependencias..."
      - npm install
  build:
    commands:
      - echo "Construyendo la aplicaci贸n..."
      - ng build --prod  # Construyo la aplicaci贸n para producci贸n
artifacts:
  files:
    - dist/browser**  # Especifico los artefactos generados para desplegar
